---
site_name: 'Business Process Module'
source_dir: '/var/www/docs/source'
site_dir: '/var/www/docs/html'
project:
  git: 'https://github.com/Icinga/icingaweb2-module-businessprocess.git'
  ref: 'tags/v2.2.0'
  target: 'businessprocess'
  docs_dir: 'doc'
  latest: true
