---
site_name: 'Director'
source_dir: '/var/www/docs/source'
site_dir: '/var/www/docs/html'
project:
  git: 'https://github.com/Icinga/icingaweb2-module-director.git'
  ref: 'master'
  target: 'director'
  docs_dir: 'doc'
  subcategories:
    Modules:
      PuppetDB:
        git: 'https://github.com/Icinga/icingaweb2-module-puppetdb.git'
        ref: 'master'
        target: 'puppetdb'
        docs_dir: 'puppetdb/doc'
      Fileshipper:
        git: 'https://github.com/Icinga/icingaweb2-module-fileshipper.git'
        ref: 'master'
        target: 'fileshipper'
        docs_dir: 'fileshipper/doc'
      vSphere:
        git: 'https://github.com/Icinga/icingaweb2-module-vsphere.git'
        ref: 'master'
        target: 'vsphere'
        docs_dir: 'vsphere/doc'
      AWS:
        git: 'https://github.com/Icinga/icingaweb2-module-aws.git'
        ref: 'master'
        target: 'AWS'
        docs_dir: 'AWS/doc'
