---
site_name: 'Elasticsearch Module'
source_dir: '/var/www/docs/source'
site_dir: '/var/www/docs/html'
project:
  git: 'https://github.com/Icinga/icingaweb2-module-elasticsearch.git'
  ref: 'tags/v0.9.0'
  target: 'elasticsearch'
  docs_dir: 'doc'
  latest: true
