---
site_name: 'Icinga 2'
source_dir: '/var/www/docs/source'
site_dir: '/var/www/docs/html'
project:
  git: 'https://github.com/Icinga/icinga2.git'
  ref: 'support/2.10'
  target: 'icinga2'
  docs_dir: 'doc'
  latest: true
